jobs:

- job: setup
  displayName: generate unique cache ID
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: none
    - bash: |
        echo "##vso[task.setvariable variable=CACHE_ID;isOutput=true]$(date)"
      displayName: Set up build constants
      name: constants

- job: cache_file
  dependsOn:
    - setup
  displayName: Populate cache
  pool:
    vmImage: macOS-latest
  variables:
    CACHE_ID: $[ dependencies.setup.outputs['constants.CACHE_ID'] ]
  steps:
  - template: .azure-pipelines/cache-file.yml

- job: restore_file
  dependsOn:
    - setup
    - cache_file
  displayName: Read back from cache
  pool:
    vmImage: macOS-latest
  variables:
    CACHE_ID: $[ dependencies.setup.outputs['constants.CACHE_ID'] ]
  steps:
  - template: .azure-pipelines/restore-file.yml
